name: Build

on:
  push:
    branches: [ "bureado-patch-1" ]
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    env:
      OFFICIAL_BUILD: 'True'
      # Set the build number in MinVer.
      MINVERBUILDMETADATA: build.${{github.run_number}}
  
    steps:
    - uses: actions/checkout@v3
    
    # - uses: ./.github/workflows/setup-dotnet.yml
    #   with:
    #     platform_name: ${{ env.RUNNER_OS }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.300

    - name: Restore dependencies
      run: dotnet restore 
      
    - name: Build
      run: dotnet build --no-restore

